name: scrcpy web

on:
  push:
    branches: [ "main" ]

  schedule:
    - cron: '0 */6 * * *'

  #pull_request:
  #  branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Cloudflared
        run: |       
          sudo mkdir -p --mode=0755 /usr/share/keyrings
          curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null

          echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared any main' | sudo tee /etc/apt/sources.list.d/cloudflared.list

          sudo apt-get update && sudo apt-get install cloudflared && sudo apt install parallel

      - name: Setup Cloudflared
        run: |
          #sudo cloudflared service install eyJhIjoiOWFjMWUxOTExMmU5ZWZmZDIzNmFlNDk1NDIyYmY2ZjgiLCJ0IjoiMTBiMjdhNDctNTdlYS00ZWM1LWIyNzctYWFlMDZkNGJmZDMzIiwicyI6Ik56RXpOemRtWVRRdFpqYzFaaTAwWldRNExUaG1Zek10WmpCa1lXTm1Zek0wT1RkayJ9
          #cloudflared tunnel run --token eyJhIjoiOWFjMWUxOTExMmU5ZWZmZDIzNmFlNDk1NDIyYmY2ZjgiLCJ0IjoiYzE0OTEyZmEtZGEyZC00MDdlLTkzODQtOWI0Njg0ODQwYzdhIiwicyI6Ik9HVm1ORFk1WWpZdE1XWm1NeTAwTUdObUxUbGpOalV0WWpVelpXSm1NbUkyWW1JeSJ9 &
          
          
      - name: Idk
        run: |
           sudo apt install openssh-server -y        
           echo 'runner:mypasswd' | sudo chpasswd
           echo -e "Port 22\nListenAddress 0.0.0.0" | sudo tee /etc/ssh/sshd_config
           sudo ssh-keygen -A
           sudo mkdir -p /run/sshd
           sudo chmod 755 /run/sshd
           sudo /usr/sbin/sshd &
           sleep 555555555
          



